package com.aoros.bagging.local.search;

import org.jamesframework.core.problems.constraints.validations.Validation;

/**
 * Custom validation object generated by the bagging constraint.
 */
public class BaggingValidation implements Validation {

    private final double curWeight;
    private final double maxWeight;

    public BaggingValidation(double curWeight, double maxWeight) {
        this.curWeight = curWeight;
        this.maxWeight = maxWeight;
    }

    @Override
    public boolean passed() {
        return curWeight <= maxWeight;
    }

    public double getCurWeight() {
        return curWeight;
    }

}
